# Generated by Django 3.2.9 on 2021-12-03 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fetcher',
            fields=[
                ('name', models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False)),
                ('enable', models.BooleanField(default=True)),
                ('sum_proxies_amount', models.IntegerField(default=0)),
                ('last_proxies_amount', models.IntegerField(default=0)),
                ('last_fetch_time', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('proxy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('protocol', models.CharField(choices=[('socks4', 'socks4'), ('socks5', 'socks5'), ('http', 'http'), ('https', 'https')], max_length=16)),
                ('ip', models.CharField(max_length=16)),
                ('port', models.IntegerField()),
                ('validated', models.BooleanField(default=False)),
                ('latency', models.FloatField(default=0)),
                ('validate_time', models.FloatField(default=0)),
                ('to_validate_time', models.FloatField(default=0)),
                ('fetcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxy_api.fetcher')),
            ],
        ),
    ]
