# Generated by Django 3.2.9 on 2021-12-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='proxy_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
